# Generated by Django 5.0 on 2024-01-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
