# Generated by Django 4.2.9 on 2024-01-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='время последнего обновления'),
        ),
    ]
